### ISSUE TITLE
这么好的东西不支持电视直播

### ISSUE THREAD

**Issue by openwrt-1983** [yzzyzz/goloradio#1]
这么好的东西不支持电视直播，实在是太可惜了，作者能不能添加上去呀？

**Comment by yzzyzz** [comment]
golo 解码性能太差，屏幕也小，看视频就太委屈自己了。
看视频还是用大屏设备吧。

**Comment by yzzyzz** [comment]
golo 解码性能太差，屏幕也小，看视频就太委屈自己了。
看视频还是用大屏设备吧。

**Comment by openwrt-1983** [comment]
弄那个标清的圆应该还是可以的，最起码还多一个功能吧，相当于收听一下伴音




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月27日(星期四) 下午4:29
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yzzyzz/goloradio] 这么好的东西不支持电视直播 (Issue #1)





 
golo 解码性能太差，屏幕也小，看视频就太委屈自己了。
 看视频还是用大屏设备吧。

**Comment by openwrt-1983** [comment]
弄那个标清的源应该还是可以的，最起码还多一个功能吧，相当于收听一下伴音
